### ISSUE TITLE
App lock

### ISSUE THREAD

**Issue by Giovanni196326** [calleluks/Tofu#82] opened 2021-06-04 04:28 UTC
Could you please add the option to lock to lock the app with face id or a password?

**Comment by eutampieri** [comment] 2021-06-04 06:46
Duplicate of #27, I fear

**Comment by p-marg** [comment] 2021-08-06 07:54
It’s a needed feature for sure.

**Comment by calleluks** [comment] 2021-09-25 06:43
Closing in favor of #27.

**Closed by calleluks** 2021-09-25 06:43 UTC
